var testList = [
    {filename:"number-tostring.htm", name:"number.toString()"},
    {filename:"typed-array-props.htm", name:"Typed array properties"},
    {filename:"pixastic-desaturate/index.htm", name:"Pixastic desaturate"},
    {filename:"JSAStar/index.htm", name:"JSA* Benchmark"},
    {filename:"bigint/index.htm", name:"jsbn BigInteger"},
    {filename:"distance-transform.htm", name:"Distance Transform"},
    {filename:"pk-sha1.htm", name:"SHA1"},
    {filename:"model2d.htm", name:"Model2D"},
    {filename:"kudoku.htm", name:"Kudoku Sudoku Solver"},
    {filename:"rayjs/index.htm", name:"Oliver's JS Raytracer"},
    {filename:"md5.htm", name:"md5"},
    {filename:"jpx2/index.htm", name:"jpeg2000 decoder"},
    {filename:"JSIL-ElementProxies/index.htm", name:"JSIL ElementProxies"},
    {filename:"JSIL-memcpy.htm", name:"JSIL memcpy"},
];
